<x-admin.layout :title="$appointment->reference">
    <x-slot:actions><a href="{{ route('admin.appointments.index') }}" class="btn-light btn-sm">All appointments</a></x-slot:actions>
    <div class="grid gap-6 lg:grid-cols-3">
        <div class="space-y-6 lg:col-span-2">
            <section class="card">
                <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="eyebrow">{{ $appointment->type?->name ?? 'Appointment' }}</p><h2 class="mt-2 font-display text-3xl">{{ $appointment->starts_at->format('l j F Y') }}</h2><p class="text-stone">{{ $appointment->starts_at->format('g:i A') }} – {{ $appointment->ends_at->format('g:i A') }}{{ $appointment->provider ? ' · '.$appointment->provider->name : '' }}</p></div><x-admin.status :status="$appointment->status" class="text-sm" /></div>
                <dl class="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="label">Patient</dt><dd><a href="{{ route('admin.patients.show', $appointment->patient) }}" class="font-semibold hover:text-gold-deep">{{ $appointment->patient->fullName() }}</a><br><a href="tel:{{ $appointment->patient->phone }}" class="text-stone">{{ $appointment->patient->phone }}</a><br><a href="mailto:{{ $appointment->patient->email }}" class="text-stone">{{ $appointment->patient->email }}</a></dd></div><div><dt class="label">Booked</dt><dd>{{ $appointment->created_at->format('j M Y, g:i A') }} via {{ $appointment->source }}@if ($appointment->confirmed_at)<br>Confirmed {{ $appointment->confirmed_at->format('j M, g:i A') }}@endif @if ($appointment->cancelled_at)<br>Cancelled {{ $appointment->cancelled_at->format('j M, g:i A') }}: {{ $appointment->cancellation_reason }}@endif</dd></div>@if ($appointment->patient_notes)<div class="sm:col-span-2"><dt class="label">Patient's notes</dt><dd class="whitespace-pre-line rounded-xl bg-sand p-3">{{ $appointment->patient_notes }}</dd></div>@endif</dl>
                <div class="mt-6 flex flex-wrap gap-2">
                    @if ($appointment->status === 'pending')<form method="post" action="{{ route('admin.appointments.status', $appointment) }}">@csrf @method('patch')<input type="hidden" name="status" value="confirmed"><button class="btn-gold btn-sm">Confirm &amp; email patient</button></form>@endif
                    @if ($appointment->isOpen())<form method="post" action="{{ route('admin.appointments.status', $appointment) }}">@csrf @method('patch')<input type="hidden" name="status" value="completed"><input type="hidden" name="notify" value="0"><button class="btn-light btn-sm">Mark completed</button></form><form method="post" action="{{ route('admin.appointments.status', $appointment) }}">@csrf @method('patch')<input type="hidden" name="status" value="no_show"><input type="hidden" name="notify" value="0"><button class="btn-light btn-sm">No show</button></form>
                    <form method="post" action="{{ route('admin.appointments.status', $appointment) }}" class="flex gap-2" onsubmit="return confirm('Cancel this appointment and email the patient?')">@csrf @method('patch')<input type="hidden" name="status" value="cancelled"><input name="reason" placeholder="Reason" class="input input-sm max-w-48"><button class="btn-rose btn-sm">Cancel</button></form>@endif
                    @if ($appointment->status === 'cancelled')<form method="post" action="{{ route('admin.appointments.status', $appointment) }}">@csrf @method('patch')<input type="hidden" name="status" value="pending"><input type="hidden" name="notify" value="0"><button class="btn-light btn-sm">Reopen as pending</button></form>@endif
                </div>
            </section>
            <section class="card"><h3 class="font-display text-2xl">Reschedule or edit</h3>
                <form method="post" action="{{ route('admin.appointments.update', $appointment) }}" class="mt-4 grid gap-4 sm:grid-cols-3">@csrf @method('patch')
                    <x-admin.field label="Date" name="date"><input name="date" type="date" value="{{ old('date', $appointment->starts_at->toDateString()) }}" class="input" required></x-admin.field>
                    <x-admin.field label="Time" name="time"><input name="time" type="time" value="{{ old('time', $appointment->starts_at->format('H:i')) }}" class="input" required step="300"></x-admin.field>
                    <x-admin.field label="Duration (min)" name="duration"><input name="duration" type="number" value="{{ old('duration', $appointment->ends_at->diffInMinutes($appointment->starts_at)) }}" min="10" max="480" step="5" class="input" required></x-admin.field>
                    <x-admin.field label="Type" name="appointment_type_id"><select name="appointment_type_id" class="input"><option value="">—</option>@foreach (\App\Models\AppointmentType::orderBy('sort')->get() as $t)<option value="{{ $t->id }}" @selected($appointment->appointment_type_id === $t->id)>{{ $t->name }}</option>@endforeach</select></x-admin.field>
                    <x-admin.field label="Provider" name="team_member_id" class="sm:col-span-2"><select name="team_member_id" class="input"><option value="">Unassigned</option>@foreach (\App\Models\TeamMember::active()->where('accepts_bookings', true)->get() as $p)<option value="{{ $p->id }}" @selected($appointment->team_member_id === $p->id)>{{ $p->name }}</option>@endforeach</select></x-admin.field>
                    <x-admin.field label="Staff notes" name="staff_notes" class="sm:col-span-3"><textarea name="staff_notes" rows="3" class="input">{{ old('staff_notes', $appointment->staff_notes) }}</textarea></x-admin.field>
                    <div class="flex flex-wrap items-center gap-4 sm:col-span-3"><button class="btn-ink btn-sm">Save changes</button><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="notify" value="1" class="check" checked>Email the patient if the time changed</label></div>
                </form>
            </section>
        </div>
        <aside class="space-y-6">
            <section class="card"><h3 class="font-display text-2xl">Patient history</h3><ul class="mt-4 divide-y divide-line text-sm">@foreach ($appointment->patient->appointments->take(8) as $h)<li class="flex items-center justify-between py-2"><a href="{{ route('admin.appointments.show', $h) }}" class="{{ $h->is($appointment) ? 'font-semibold' : '' }} hover:text-gold-deep">{{ $h->starts_at->format('j M Y') }}<span class="block text-xs text-stone">{{ $h->type?->name }}</span></a><x-admin.status :status="$h->status" /></li>@endforeach</ul></section>
            <section class="card text-sm"><h3 class="font-display text-2xl">Patient link</h3><p class="mt-2 text-stone">The patient can view or cancel at:</p><input readonly value="{{ $appointment->manageUrl() }}" class="input input-sm mt-2 font-mono text-xs" onclick="this.select()"></section>
            @if ($appointment->status !== 'completed')<form method="post" action="{{ route('admin.appointments.destroy', $appointment) }}" onsubmit="return confirm('Delete this appointment record entirely?')" class="text-right">@csrf @method('delete')<button class="text-xs font-semibold text-rose hover:underline">Delete record</button></form>@endif
        </aside>
    </div>
</x-admin.layout>
