<x-admin.layout :title="$patient->fullName()">
    <x-slot:actions><a href="{{ route('admin.appointments.create', ['patient' => $patient->id]) }}" class="btn-gold btn-sm">Book appointment</a><a href="{{ route('admin.patients.edit', $patient) }}" class="btn-light btn-sm">Edit</a></x-slot:actions>
    <div class="grid gap-6 lg:grid-cols-3">
        <section class="card text-sm"><dl class="space-y-3"><div><dt class="label">Phone</dt><dd><a href="tel:{{ $patient->phone }}" class="font-semibold">{{ $patient->phone ?: '—' }}</a></dd></div><div><dt class="label">Email</dt><dd><a href="mailto:{{ $patient->email }}" class="font-semibold">{{ $patient->email ?: '—' }}</a></dd></div><div><dt class="label">Date of birth</dt><dd>{{ $patient->date_of_birth?->format('j M Y') ?? '—' }}{{ $patient->date_of_birth ? ' ('.$patient->date_of_birth->age.')' : '' }}</dd></div><div><dt class="label">Gender</dt><dd>{{ $patient->gender ?: '—' }}</dd></div><div><dt class="label">Source</dt><dd>{{ ucfirst($patient->source) }} · since {{ $patient->created_at->format('j M Y') }}</dd></div><div><dt class="label">Marketing</dt><dd>{{ $patient->marketing_opt_in ? 'Opted in' : 'Not opted in' }}</dd></div></dl>@if ($patient->notes)<div class="mt-4 rounded-xl bg-sand p-3 whitespace-pre-line">{{ $patient->notes }}</div>@endif</section>
        <section class="card p-0 lg:col-span-2"><div class="px-5 py-4"><h2 class="font-display text-2xl">Appointments</h2></div><table class="table"><thead><tr><th>When</th><th>Type</th><th>With</th><th>Status</th></tr></thead><tbody>@forelse ($patient->appointments as $a)<tr><td><a href="{{ route('admin.appointments.show', $a) }}" class="font-semibold hover:text-gold-deep">{{ $a->starts_at->format('D j M Y, g:i A') }}</a></td><td>{{ $a->type?->name }}</td><td>{{ $a->provider?->name ?? '—' }}</td><td><x-admin.status :status="$a->status" /></td></tr>@empty<tr><td colspan="4" class="text-stone">No appointments yet.</td></tr>@endforelse</tbody></table>
            @if ($patient->inquiries->isNotEmpty())<div class="border-t border-line px-5 py-4"><h2 class="font-display text-2xl">Enquiries</h2><ul class="mt-3 divide-y divide-line text-sm">@foreach ($patient->inquiries as $i)<li class="py-2"><a href="{{ route('admin.inquiries.show', $i) }}" class="font-semibold hover:text-gold-deep">{{ $i->created_at->format('j M Y') }} · {{ $i->service ?: 'General' }}</a> <x-admin.status :status="$i->status" /><p class="mt-1 line-clamp-2 text-stone">{{ $i->message }}</p></li>@endforeach</ul></div>@endif
        </section>
    </div>
</x-admin.layout>
