<x-site.layout title="Emergency Dentist" description="Dental emergency in Trinidad? Smile Inn Dental in St. James provides prompt, compassionate care for toothaches, broken teeth and urgent dental needs.">
@php($clinic = config('clinic'))
<section class="bg-rose text-white">
    <div class="wrap grid gap-10 py-16 lg:grid-cols-12 lg:items-center lg:py-24">
        <div class="lg:col-span-7"><p class="eyebrow text-white/80">Emergency services · St. James, Port of Spain</p><h1 class="h-display mt-5 text-white">Get immediate relief and expert care.</h1><p class="lede mt-6 text-white/85">{{ $service->intro }}</p><div class="mt-9 flex flex-wrap gap-3"><a href="tel:{{ $clinic['phone_href'] }}" class="btn bg-white text-rose hover:bg-ivory btn-lg"><x-icon name="phone" class="size-5" />Call {{ $clinic['phone'] }}</a><a href="{{ route('book', ['type' => 'emergency-appointment']) }}" class="btn ring-1 ring-white/50 text-white hover:bg-white/10 btn-lg">Book an emergency slot</a></div></div>
        <div class="rounded-3xl bg-white/10 p-7 ring-1 ring-white/20 lg:col-span-5"><p class="eyebrow text-white/80">While you are on your way</p><ul class="mt-5 space-y-4 text-sm">@foreach ([['Knocked-out tooth', 'Keep it in milk or saline. Do not scrub it. Time is critical: come straight in.'], ['Severe toothache', 'Rinse with warm salt water. Take over-the-counter pain relief if you can. Avoid very hot or cold food.'], ['Broken or chipped tooth', 'Keep any pieces, rinse gently and cover sharp edges with sugar-free gum.'], ['Something lodged between teeth', 'Rinse and floss gently. Never use sharp objects.']] as [$h, $t])<li><p class="font-semibold">{{ $h }}</p><p class="text-white/80">{{ $t }}</p></li>@endforeach</ul><p class="mt-6 text-xs text-white/70">We see emergencies during opening hours, Monday to Saturday 8:00 AM to 3:30 PM. Call first so we can prepare for you.</p></div>
    </div>
</section>
<section class="section">
    <div class="wrap"><x-site.heading eyebrow="Common emergency scenarios" title="What we treat, and what we will do." /><div class="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach ($service->treatments as $t)<div class="card reveal"><span class="inline-flex size-9 items-center justify-center rounded-xl bg-rose/10 text-rose"><x-icon name="alert" class="size-4.5" /></span><h2 class="mt-4 font-display text-xl font-medium">{{ $t['name'] }}</h2><p class="mt-2 text-sm text-stone">{{ $t['description'] }}</p></div>@endforeach</div></div>
</section>
<section class="wrap pb-24"><div class="rounded-[2rem] bg-ink p-10 text-ivory sm:p-14"><div class="grid gap-8 lg:grid-cols-2 lg:items-center"><div><p class="eyebrow text-gold">Schedule your emergency appointment now</p><h2 class="h-section mt-4 text-ivory">Quick, quality care, with no judgement.</h2></div><div class="flex flex-wrap gap-3 lg:justify-end"><a href="tel:{{ $clinic['phone_href'] }}" class="btn-gold btn-lg"><x-icon name="phone" class="size-4" />{{ $clinic['phone'] }}</a><a href="https://wa.me/{{ $clinic['whatsapp'] }}" target="_blank" rel="noopener" class="btn-lg btn bg-white/10 text-ivory ring-1 ring-white/20 hover:bg-white hover:text-ink"><x-icon name="whatsapp" class="size-4" />WhatsApp</a></div></div></div></section>
</x-site.layout>
